Migrating references from dockerhub/ixiacom repo  to ghcr/otg
open-traffic-generator/ixia-c pull request #91
Opened 2022-08-10 12:41 UTC by biplamal

2022-08-12 17:33 UTC, ankur-sheth commented on docs/deployments.md
> +All these services are available as docker image on [GitHub Open-Traffic-Generator repository](https://github.com/orgs/open-traffic-generator/packages). Please check [Ixia-c Releases](releases.md) to
...as docker image on... --> as docker images on...

2022-08-12 17:36 UTC, ankur-sheth requested changes
Please also add an item on docs/news.md that starting now images will be posted on GHCR.  We will continue to post on Docker Hub for the next 3 months and then stop posting there completely.  
Once this PR is submitted, we should also announce the same on the Ixia-c slack so that people can migrate.

2022-08-16 04:21 UTC, biplamal commented on docs/deployments.md
> +All these services are available as docker image on [GitHub Open-Traffic-Generator repository](https://github.com/orgs/open-traffic-generator/packages). Please check [Ixia-c Releases](releases.md) to
Done

2022-08-16 20:10 UTC, ankur-sheth reviewed
Still need to add a section to the news.md.

2022-08-18 04:35 UTC, merged